### ISSUE TITLE
Items being thrown when typing into terminal

### ISSUE THREAD

**Issue by Hardeh** [Spantle/ThrowEverything#1]
Apparently pressing "R" still registers as throw while you're using the terminal

**Comment by Spantle** [comment]
Sorry about that, fixed in dde2f625ae45c499a77d7a7db2640ae51d3dc452 released in v0.3.0

**Comment by Fl4sHNoX** [comment]
I would like to report that I currently experience this issue but only with certain items like the Walkie-Talkie, here's a video to show the issue happening:

https://github.com/Spantle/ThrowEverything/assets/3759901/54485fa7-232b-4c68-896f-2cb889c356fc
